name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install sbt
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install sbt

    - name: Cache sbt
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Build and test
      run: sbt clean test

    - name: Assembly JAR
      run: sbt assembly

    - name: Build Docker image
#      run: docker build -t spotify-recommender .
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spotify-recommender:${{ github.sha }} .

    # Optionally push Docker image to a registry here
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/spotify-recommender:${{ github.sha }}

      # Optional: Deploy to Kubernetes
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl set image deployment/spotify-recommender spotify-recommender=${{ secrets.DOCKERHUB_USERNAME }}/spotify-recommender:${{ github.sha }}